name: iOS-ipa-build

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Remove Junk Files
        run: |
          buildozer ios clean
          find /Users/runner/work/mypdf/mypdf/.buildozer/ios/platform/kivy-ios/build/sdl2_mixer/ -type f -name "*.sh" -delete

      - name: Build with Buildozer
        run: |
          python3 --version
          python3 -m venv .venv
          source .venv/bin/activate
          
          python3 -m pip install --upgrade buildozer
          python3 -m pip install sdl2_ttf sdl2_mixer

      - name: brew packages in its path
        run: |
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake
          echo 'export GST_PLUGIN_PATH="~/.local/lib/gstreamer-1.0"' >> ~/.bashrc
          source ~/.bashrc
          
      - name : varify gst plugin path
        run: |
          echo $GST_PLUGIN_PATH
          source .venv/bin/activate
          python3 -m pip install --upgrade pip virtualenv kivy-ios
          python3 -m pip install docutils
          
      - name: build ios ipa
        run: |
          source .venv/bin/activate
          buildozer -v ios debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk

      
